// Code generated by "stringer -type=Event"; DO NOT EDIT.

package nui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Surface-1]
	_ = x[Position-2]
	_ = x[Size-4]
	_ = x[View-8]
	_ = x[Touch-16]
	_ = x[Nada-32]
}

const (
	_Event_name_0 = "SurfacePosition"
	_Event_name_1 = "Size"
	_Event_name_2 = "View"
	_Event_name_3 = "Touch"
	_Event_name_4 = "Nada"
)

var (
	_Event_index_0 = [...]uint8{0, 7, 15}
)

func (i Event) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Event_name_0[_Event_index_0[i]:_Event_index_0[i+1]]
	case i == 4:
		return _Event_name_1
	case i == 8:
		return _Event_name_2
	case i == 16:
		return _Event_name_3
	case i == 32:
		return _Event_name_4
	default:
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
